name: ericfeunekes
favicon: null
layout_spectrum: 0.66634
typography_spectrum: 0.9354839
title: start-ups and law
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f30044'
    - '#78b8ff'
    - '#1f2186'
    - '#ffffff'
    - '#444444'
  brandStrength: 0.75
  lightness: 0.7759857
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
