name: ericfeunekes
favicon: null
layout_spectrum: 0.92676
typography_spectrum: 0.8916
title: start-ups and law
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f30044'
    - '#78b8ff'
    - '#1f2186'
    - '#ffffff'
    - '#444444'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
