title: start-ups and law
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.749104
  brandStrength: 0.9354839
  lightness: 0.7759857
  brandColors:
    - '#f30044'
    - '#78b8ff'
    - '#1f2186'
    - '#ffffff'
    - '#444444'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: ericfeunekes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9354839
layout_spectrum: 0.4964158
